% Script to extract the ECG signal
%
% INPUT:  
% - Select the raw bdf file of one participant (after execution of the script Script1_ECG_R_peak_detection_and_mark_EEG.m)
% - Specify if the best ECG channel were EXG1-EXG2 (ecg channel 1) or
% EXG3-EXG4 (ecg channel 2) according the log file generated by the script Script1_ECG_R_peak_detection_and_mark_EEG.m
% 
% OUTPUT
% - '*ECG.eph' file (* is replace by the input bdf file name) which contain only the ECG signal mean centred to shift the 0 position (more easy to read).  
% - '*ECG.eph.mrk' file (* is replace by the input bdf file name) which is the same marker as the input file (already manually corrected). 



%% Initialization
clear all
% Mapping the folder with the function used by this script
addpath(genpath('functions_needed')); %add path with sub-directories


%input EEG folder
[file,path]=uigetfile('*.bdf', 'Select the EEG/ECG recording file of one participant','MultiSelect','off');

%tell which are the best ECG channel
answer1=questdlg('Which is the best ECG channel in this file', 'EXG1-EXG2','EXG1-EXG2','EXG3-EXG4','EXG3-EXG4');
if strcmp (answer1, 'EXG3-EXG4')
    bestECGchannel=2;
else
    bestECGchannel=1;
end


%load EEG Data
file=fullfile(path,file);
disp(file);
[data,NumChan,ChanLabels,SamplingRate,~,eventVectorUnique]=open_bdf_modified(file); %open the recording file

startData=1;
[endData,~]=size(data);

%% Load ECG

%Extraction of each ECG channel
EXG1=data(startData:endData,find(strcmp(ChanLabels, 'EXG1')==1))';
EXG2=data(startData:endData,find(strcmp(ChanLabels, 'EXG2')==1))';
EXG3=data(startData:endData,find(strcmp(ChanLabels, 'EXG3')==1))';
EXG4=data(startData:endData,find(strcmp(ChanLabels, 'EXG4')==1))';

switch bestECGchannel
    case 1
        ecg=EXG1-EXG2; 
    case 2
        ecg=EXG3-EXG4;
end

%% R-peak loading

%concatenate both marker
MRKtot=open_mrk(strcat(file,'.mrk'));   


%% SaveECG
ecgFileName=fullfile(strcat(file(1:end-4),'_ECG.eph'));
save_eph(ecgFileName,(ecg-mean(ecg))',SamplingRate,1); %to a reading for easey, I mean center the ECG
WriteMRK_univeral (cell2mat(MRKtot(:,1)), cell2mat(MRKtot(:,3)), strcat(ecgFileName,'.mrk'), 0); 
    

